Add additional VIP classes
pulp-platform/apb pull request #5
Opened 2021-06-08 15:09 UTC by meggiman

This commit adds two new apb vip classes to apb_test:
apb_rand_slave and apb_rand_master

They are implemented similar in style like the ones present in the https://github.com/pulp-platform/axi project and perform random transactions/responses on the provided APB_DV buses. In contrast to the ones in the axi project, they use SV mailboxes to record all incoming and outgoing transactions/read responses so an external TB can probe them in a threadsafe manner. Both classes are tested in a small TB for a new apb_cdc module that will be contributed in a follow-up PR.

2021-06-08 15:49 UTC, accuminium requested changes
This is very useful, thanks @meggiman!

I have a few (mostly minor) comments and requests.

2021-06-08 15:49 UTC, accuminium commented on src/apb_test.sv
> +  endclass; // apb_read_request
```suggestion
  endclass; // apb_response
```
What is the use of such comments, especially for so such small blocks? As this example shows, these comments are frequently outdated. I think they add more maintenance burden than readability gain.

2021-06-08 15:49 UTC, accuminium commented on src/apb_test.sv
> +      while (apb.psel != 1 && apb.penable != 1) begin cycle_end(); cycle_start(); end
```suggestion
      while (!apb.psel) begin cycle_end(); cycle_start(); end
      while (!apb.penable) begin cycle_end(); cycle_start(); end
```
The assertion of `psel` starts the Setup phase, and the assertion of `penable` starts the Access phase. According to the specification, there is one clock cycle between the start of the two phases.

2021-06-08 15:49 UTC, accuminium commented on src/apb_test.sv
> +        if (request.pwrite == 1) begin
```suggestion
        if (request.pwrite) begin
```

2021-06-08 15:49 UTC, accuminium commented on src/apb_test.sv
> +    endtask : run // run
```suggestion
    endtask
```
Half of this line consists of redundant information.  I suggest to KISS and DRY ;-)

2021-06-08 15:49 UTC, accuminium commented on src/apb_test.sv
> +    endtask : rand_wait // rand_wait
```suggestion
    endtask
```

2021-06-08 15:49 UTC, accuminium commented on src/apb_test.sv
> +    // Stimuli application and test time
```suggestion
```

2021-06-08 15:49 UTC, accuminium commented on src/apb_test.sv
> +    // Stimuli application and test time
```suggestion
```

2021-06-08 15:49 UTC, accuminium commented on src/apb_test.sv
> +        if (request.pwrite == 1'b1) begin
```suggestion
        if (request.pwrite) begin
```

2021-06-08 15:49 UTC, accuminium commented on src/apb_test.sv
> +          $info("Sending write reqeust with addr: %h, pstrb: %b and pwdata: %h", request.paddr, request.pstrb, request.pwdata);
```suggestion
          $info("Sending write request with addr: %h, pstrb: %b and pwdata: %h", request.paddr, request.pstrb, request.pwdata);
```

2021-06-08 16:26 UTC, meggiman commented on src/apb_test.sv
> +  endclass; // apb_read_request
No use. That's just emacs verilog-mode adding those to the file by default :-)

2021-06-08 16:30 UTC, meggiman commented on src/apb_test.sv
> +      while (apb.psel != 1 && apb.penable != 1) begin cycle_end(); cycle_start(); end
I see. However, for a correctly behaving APB master, this should not really make a difference since psel and penable are supposed to be asserted simultaneously for at least one cycle. It just stalls masters for one additional cycles that do not comply with this rule.

2021-06-08 16:40 UTC, meggiman commented
Thank's for the review. I committed your change suggestions.

2022-12-02 15:04 UTC, paulsc96 approved these changes

2022-12-02 15:05 UTC, merged