Apb cdc
pulp-platform/apb pull request #6
Opened 2021-06-08 15:12 UTC by meggiman

This PR adds an apb_cdc module (struct + interface version) using cdc_gray_fifos from the common cells repository in both direcionts. A small FSM on src and dst side converter between APB request/response and the cdc's ready/valid handshaking. 
The IP is verified using constrained randomized testing using the new VIPs in PR #5. Thus this PR depends on merging #5 which is why it remains in draft state for the moment.

2021-06-08 16:09 UTC, accuminium requested changes
Also very useful, thanks @meggiman!

I have a few (mostly minor) comments and requests.

2021-06-08 16:09 UTC, accuminium commented on src/apb_cdc.sv
> +        dst_req_o.penable = 1'b1;
The APB protocol separates the Setup phase, which starts by asserting the `psel` signal, from the Access phase, which starts by asserting the `penable` signal, by one clock cycle. So you need to go to a separate `Dst_Setup` state first, right?

2021-06-08 16:09 UTC, accuminium commented on test/tb_apb_cdc.sv
> +  logic                            mst_done = 1'b0;
```suggestion
  logic mst_done = 1'b0;
```

2021-06-08 16:34 UTC, meggiman commented on src/apb_cdc.sv
> +//              Some of the registers can be configured to be read only.
Done

2021-06-08 16:37 UTC, meggiman commented on src/apb_cdc.sv
> +        dst_req_o.penable = 1'b1;
I don't think this is necessary. It just introduces additional toggling. But waiting for both, psel and penable to be asserted before sampling the request data should be enough. Or am I missing something? If the master is protocol compliant using an additional state is just introducing additional toggling in the FSM one cycle prior to the actual request to the CDC fifo.

2021-06-08 16:42 UTC, meggiman commented
Thanks for the review. I changed the description of the module and committed the changes you suggested. However, for the introduction of an additional Setup state I am not sure this is really necessary (see comment in review thread).

2021-06-09 07:46 UTC, meggiman commented on src/apb_cdc.sv
> +        dst_req_o.penable = 1'b1;
Ah wait... That's the output FSM. But there, the penable is asserted in the Dst_Idle state (it's a mealy FSM) and penable is asserted in the Dst_Access state. So Idle and setup state are merged and setup starts once the CDC output valid signal is raised.

2022-12-02 15:29 UTC, paulsc96 approved these changes

2022-12-02 15:29 UTC, merged